internxt/send-web

src/services/upload.service.ts
- Sends the unique code to be able to share that code via mail.
=> [_]: fix/send-code-for-mail

public/index.html
Use Internxt-owned analytics platform.
=> Analytics migration

src/views/HomeView.tsx
=> [-]:(fix) Update HomeVIew.tsx

src/App.tsx, src/Layout.tsx, src/components/CardBotton.tsx, src/components/FileArea.tsx, src/components/send/FaqSection.tsx, src/components/send/FeatureSection.tsx, src/components/send/InfoSection.tsx, src/styles/index.css, src/views/HomeView.tsx
Designs updated:
* Mobile
* Tablet
* Laptop / desktop
=> [WT-153](fix) Designs finished

src/Layout.tsx
Resize bug in "upload files" Card fixed.
=> [_]:(fix) Resize bug fixed

src/Layout.tsx
min-height change from 800 to 700
=> [_]: (fix) Height resize changed from 800 to 700

public/index.html
Metatag-description updated for provide more details about the LP.
=> [_]: (fix) Update metatag-description

public/index.html
Meta title changed from "Internxt Send" to "Internxt Send – Securely Send Large Files for Free"
=> [_]: (feat)Update meta title

src/components/send/InfoSection.tsx
Cards in InfoSection fixed for Safari because the image did not fit on the card.
=> [_]: (fix) Info cards fixed for Safari

package.json, src/components/Dropdown.tsx, src/components/FileArea.tsx, src/styles/index.css, yarn.lock
- Updated package.json
- Added dropdown menu when adding more items
=> [_]: Feature added dropdown menu when adding more items

src/services/download.service.ts
=> [WT-156] Fix/Null zip name

src/Layout.tsx, src/components/FileArea.tsx, src/views/HomeView.tsx
"Upload files" component centered in mobile view.
=> [_]:fix/upload-files-component-centered

src/components/FileArea.tsx, src/views/HomeView.tsx
"upload box" centered when "send email" is selected.
=> [_]: fix/Updating-"upload file/folder"-box

.github/workflows/cd-to-share.yml, infrastructure/share/share.Dockerfile, infrastructure/share/share.env, src/App.tsx, src/Layout.tsx, src/components/send/InfoSection.tsx, src/react-app-env.d.ts, src/services/upload.service.ts
- Modifies React code to graph the /s prefix
- Adds dockerfile
- nginx config from secrets
- enables CD
=> [WT-160]: Enables config so that share.internxt.com/s works

src/Layout.tsx
Logo redirects to internxt.com instead of send.internxt.com
=> [_]: fix/update-logo-link

src/assets/lang/en/footer.json, src/components/Button.tsx, src/components/FileArea.tsx, src/components/footer/Footer.tsx
Update Footer and buttons design.
=> [_]: fix/Update Buttons and footer design

package.json
Commands required for deployment added.
=> [_]: feat/Deploy project in Vercel

src/components/Card.tsx, src/views/HomeView.tsx
=> [_]: Fix/card content 

public/index.html, src/Layout.tsx, src/assets/lang/en/footer.json, src/components/footer/Footer.tsx, src/lib/urls.ts, src/views/DownloadView.tsx
The design of the downloaded file card has been updated:
* Modified icon (weight and size)
* Modified text (updated title and added description)
Some changes to improve the SEO:
* Canonical URL added
* H1 tag added
=> [MKT-143]: Feat/update layout for download file flow

src/Layout.tsx
Overflow for images in the HeroSection has been fixed (fixed by adding overflow-hidden).
=> [MKT-180]: fix/Send behaviour

src/assets/lang/en/footer.json, src/assets/lang/en/navbar.json, src/components/Navbar/Navbar.tsx, src/components/footer/Footer.tsx, src/lib/urls.ts
Add new pages to the footer:
* Open source
* Media area
* Affiliates
Navbar has also been updated:
* Our values 
* Privacy
* Open source
=> [MKT-183]: feat/update footer.json

src/components/Navbar/Navbar.tsx, src/styles/index.css
Fixes:
* Hide the GR badge
* Fix the Caret Down icon for Our values (navbar).
=> [_]: fix/style issues

src/Layout.tsx, src/components/FileArea.tsx, src/components/Navbar/Navbar.tsx, src/components/footer/Footer.tsx, src/views/HomeView.tsx
The card has been fixed for mobile view.
Photos has been removed from Navbar, Footer and Layout.
=> [_]: fix/small issues

public/index.html, src/assets/lang/en/footer.json, src/assets/lang/en/navbar.json, src/components/Navbar/Navbar.tsx, src/components/footer/Footer.tsx, src/lib/urls.ts, src/react-app-env.d.ts, src/services/analytics.service.ts, src/views/HomeView.tsx
- Add tracks when sending email or creating links
- Add VPN link to Navbar and Footer components.
- Add pCloud Alternative link to footer (Resources section)
=> [_]: feat/add tracks to see usage

.github/workflows/cd.yml
Now the deployment of the Send Web App will be on Cloudflare Pages
=> [_]: feat/deploy-on-cloudflare

src/assets/lang/en/footer.json, src/components/footer/Footer.tsx, src/lib/urls.ts
Use Cases and Library links have been removed.
=> [_]: feat/remove Use Cases and Library links

.github/workflows/cd.yml
Add the environment variables before compiling the project (`yarn build`) to publish the correctly generated build folder in Cloudflare.
=> [_]: ci/env variables before compiling the project and deploying to Cloudflare

.github/workflows/cd.yml
Deleted unused variables since they are not longer needed.
=> [_]: cd/remove unused environment variables when creating the .env

package.json, src/App.test.tsx, src/services/upload.service.test.ts, src/services/upload.service.ts, src/views/HomeView.tsx, vitest.config.js, yarn.lock
Generate the recaptcha token just before requesting the shared links, so that the token does not expire and the call can be made without any problem.
Added tests for the uploadFilesAndGetLink() function and specifically for storeSendLinks().
=> [_]: feat/get the captcha token just before to request the shared link
